blanco:
  container_name: blanco-source
  build: ./docker/blanco
  volumes:
    - ./source:/var/www
  links:
    - testredis

nginx:
  container_name: blanco-nginx
  build: ./docker/nginx
  volumes:
    - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
  volumes_from:
    - blanco
  ports:
    - "8080:80"
  links:
    - fpm

fpm:
  container_name: blanco-php-fpm
  build: ./docker/php-fpm
  working_dir: /
  volumes_from:
    - blanco

testredis:
  container_name: test-redis
  build: ./docker/redis
  ports:
    - 6379:6379