defaultredis:
  container_name: defaut-redis
  build: ./docker/redis
  ports:
    - 6379:6379

fpm:
  container_name: blanco-php-fpm
  build: ./docker/php-fpm
  working_dir: /
  volumes:
    - ./source:/var/www
  links:
    - defaultredis

nginx:
  container_name: blanco-nginx
  build: ./docker/nginx
  volumes:
    - ./docker/nginx/config/nginx.conf:/etc/nginx/conf.d/nginx.conf
  volumes_from:
    - fpm
  ports:
    - "8080:80"
  links:
    - fpm

testredis:
  container_name: test-redis
  build: ./docker/redis
  ports:
    - 6380:6379